# Generated by Django 4.1.4 on 2022-12-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genpass',
            options={'ordering': ['user'], 'verbose_name': 'genpass', 'verbose_name_plural': 'liste mots de passe'},
        ),
    ]
