# Generated by Django 4.1.1 on 2022-10-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('date_created_on', models.DateTimeField(auto_now_add=True)),
                ('project_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=30)),
                ('project_thumbnail', models.ImageField(default='images/portfolio/project/default.jpg', upload_to='images/portfolio/project/')),
                ('project_url', models.URLField(default='#')),
                ('category', models.CharField(choices=[('L', 'Laptop'), ('D', 'Desktop'), ('M', 'Mobile'), ('O', 'Other')], default='L', max_length=10)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_created_on'],
            },
        ),
    ]
